### PR TITLE
mbedtls: allow private-key from memory

### PR DESCRIPTION
**Pull request by doublex**
@willco007 

Thanks a lot!
The "trailing whitespaces" from https://github.com/libssh2/libssh2/pull/358

### CODE REVIEW

**Comment by willco007** [comment]
Looks like you still have some lines that are over 80 characters so the linter is failing. Also, there is no need to close this PR, just update your branch and it will automatically update the PR. :)

**Comment by doublex** [comment]
@willco007 
Thanks a lot.
I have added a variable to store the "password-length"

**Comment by doublex** [comment]
You simply add a another git-commit?

**Comment by willco007** [comment]
Yup, just push another update to the same branch and it will be looped in automatically.

**Comment by doublex** [comment]
@willco007 
Thanks for your help.

**Pull request merged**
