### PR TITLE
Add OS/400 support

### PR DESCRIPTION
**Pull request by monnerat**
Hi,
This pull request adds support for OS/400 and a new IBM QC3 crypto library interface.
There are specific build scripts: they produce an ASCII based library. Currently, there is no support for calling directly with EBCDIC.
I've tested it with libcurl and it works perfectly using password or key (RSA only).
No support for password-encrypted keys yet.

In addition, there is a new docs/HACKING.CRYPTO file that can help other people wanting to design a new crypto library interface.

Thanks for considering it.
Patrick

### CODE REVIEW

**Comment by bagder** [comment]
Wow, this is massive. Thanks a lot.

**Comment by monnerat** [comment]
Hi Daniel,
> Wow, this is massive. Thanks a lot.
You're welcome :-)
Yes, it's massive because:
- There are > 2000 lines for the new crypto library interface (IBM API requires a lot of preparation before calls).
- The specific OS/400 C code + compilation scripts are ~900 lines.
- The ILE/RPG prototypes are ~2500 lines.
- The HACKING.CRYPTO document is about 600 lines.
- It mainly consists of new material: updates to the existing modules have been kept to a minimum.
- It's a 10 weeks work.
Patrick

I'll probably write more in a middle near future, mainly to support encrypted private keys and EBCDIC.

**Comment by monnerat** [comment]
The additional commits implement string transcoding (os400 only) and encrypted private keys support.
This is massive again since the Qc3 library is unaware of encrypted PKCS#8 and PKCS#5: these are thus decoded by the os400qc3.c wrapper.
Please note that MD2, RC5 and DSA are not implemented in Qc3 and thus, not supported.
I have no plan to emulate them.

Any chances to get this into the master repo ?

**Comment by bagder** [comment]
I'm ready to get this merged. Can you just rebase it first please? I got problems applying it just now.

**Comment by monnerat** [comment]
Conflicts resolved and os400 branch rebased now.
Thanks for your action.

**Comment by bagder** [comment]
Thanks a lot, nice and clean work. This is now merged as of commit 77d825ac9378.

**Comment by monnerat** [comment]
Many thanks to you :-)
________________________________

**Pull request closed without merging**
