### PR TITLE
[Ready for Review] Add agent forwarding implementation

### LINKED ISSUE #185: Agent forwarding
Is there any interest in implementing agent forwarding functionality in libssh2? At one point a patch was submitted (https://www.libssh2.org/mail/libssh2-devel-archive-2012-03/0114.shtml) but it looks like it wasn't merged in (https://www.libssh2.org/mail/libssh2-devel-archive-2012-03/0121.shtml).

### PR DESCRIPTION
**Pull request by pkittenis**
Hello,

This PR implements SSH agent forwarding support via `libssh2_channel_request_auth_agent`. It is based on [Mr Hashimoto's patch in mailing list](https://www.libssh2.org/mail/libssh2-devel-archive-2012-03/0114.shtml) with changes/additions for correctness (primarily, the message was incorrect in the patch).

Example file has been updated to use agent auth and added to cmake list.

Also added integration test `tests/test_agent_forward_succeds.c` and to cmake list which is passing (needs #218 for cmake build to succeed)

Let me know if anything else needed. Agent forwarding is one of the only "core" features missing in `libssh2` so would be good to get it implemented. Thanks for the awesome library.

Resolves  #185

### CODE REVIEW

**Comment by pkittenis** [comment]
Looks like there are some unrelated errors in [some builds](https://travis-ci.org/libssh2/libssh2/jobs/290552890)

```
dpkg: error processing package oracle-java9-installer (--configure):

subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:

oracle-java9-installer
```

**Comment by pkittenis** [comment]
Appveyor failures also look unrelated:

```Cannot open include file: 'netinet/in.h': No such file or directory``` and others including `unistd.h` which is not available on windows platforms.

**Comment by pkittenis** [comment]
Is anyone available to review this PR? 

One thing that has not been tested is the behaviour with a non-OpenSSH server.

**Comment by pkittenis** [comment]
Latest changes: Support windows builds for agent fwd example. Appveyor tests now pass.

**Comment by willco007** [comment]
I've confirmed the patch works great. Small request; could you correct the spelling of succeed in `test_agent_forward_succeds.c`.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the review! Will make the changes above.

Before merging will need to verify non-openssh compatibility. Have had multiple reports of this code failing to request auth agent on different non-openssh servers, which as above was not tested. 

Whether that's because of lack of support on server or issue with code not sure yet, to be confirmed.

**Comment by willco007** [comment]
I've been using this in a private fork and it is working with non-openssh servers. There was an issue with the string `auth-agent-req@openssh.com` being `auth-agent-reqatopenssh.com` which was breaking compatibility, but it was fixed at some point along the line.

**Comment by bagder** [comment]
@willco007 so you're a :+1: for merging this then I take it?

**Comment by bagder** [comment]
@pkittenis it'd be cool if you rebased this and pushed again since the new travis builds will find bnoth code style warnings and compiler warnings on the code and example.

**Comment by willco007** [comment]
@bagder Yes, working well here.

**Comment by pkittenis** [comment]
Cool, thanks for testing. Will rebase and make changes above.

**Comment by pkittenis** [comment]
Some linting failures, will update.

**Comment by willco007** [comment]
@pkittenis Would you mind fixing up the linting errors, it would be great to get this into the 1.9 release.

**Comment by pkittenis** [comment]
Yup, keen to get it in too. Will fix up the linting errors this weekend.

**Comment by pkittenis** [comment]
Have updated for linting changes plus rebased on latest master. Let me know if anything else needed - excuse the delay.

**Comment by pkittenis** [comment]
Ping @willco007 - anything else needed on this?

**Pull request merged**
