### PR TITLE
Issues 140+141+142+143

### PR DESCRIPTION
**Pull request by doublex**
I didn't succeed to create 4 pull requests...

### CODE REVIEW

**Comment by alamaison** [comment]
Thanks, @doublex.  The code changes look fine.  Before I merge this, could you update the commits to use your name instead of 'Your Name' so that commits can be attributed correctly?  Or just tell me your name and I'll make the changes

**Comment by doublex** [comment]
@alamaison
Could you make the commits?
Thanks a lot!

**Comment by alamaison** [comment]
I certainly can, but I need to know your name to update the commits

**Comment by doublex** [comment]
Created 4 pull requests instead:
158 + 159 + 160 + 161

**Pull request closed without merging**
