### PR TITLE
Add RSA-SHA2 support for the mbedtls backend

### PR DESCRIPTION
**Pull request by gbaraldi**
Should fix https://github.com/libssh2/libssh2/issues/687.

I basically did some pattern matching from https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce. I'm not familiar with the libssh2 codebase so please do tell if there is something to be changed.

### CODE REVIEW

**Comment by gbaraldi** [comment]
@willco007 Running it locally it seems to work fine, however the builtin test suite fails using mbedtls even without modifications.

**Comment by willco007** [comment]
@gbaraldi yeah, AppVeyor is a bit temperamental and has transient failures. Your PR looks good to me.

**Comment by willco007** [comment]
@gbaraldi Are you happy with where this is at?  Is this ready to land?

**Comment by gbaraldi** [comment]
For me it's ready, it passes our test cases that were failing before and doesn't seem to have broken other things.

**Comment by gbaraldi** [comment]
@willco007 Just as a question since this fix is pretty important for us at julia. Do you have a timeline for a new release tag, I imagine 1.11?

**Comment by willco007** [comment]
@gbaraldi yup, the release is ready, we just need to put it together when we have a moment.

**Pull request merged**
