### PR TITLE
src: fix checksrc warnings

### PR DESCRIPTION
**Pull request by vszakats**
Use `checksrc.pl` from the curl project, with (for now) suppressed long line warnings and indentation set to 4 spaces. Fixes are whitespace for the most part.

Warning count went down from 2704 to 0 (2 suppressed.)

Also fix codespell typos, two non-ANSI C89 comments and a stray tab in `include/libssh2.h`.

### CODE REVIEW

**Comment by bagder** [comment]
Lovely @vszakats, me like! Maybe you could provide the script in a separate PR so that others can start playing with it too?

Do you think its possible to make the different styles as configurable options so that we can share checksrc code between the projects or is it easier to just make a separate one here?

**Comment by vszakats** [comment]
Good idea, I'll add the script in a next PR.

The only difference compared to the original curl version, is that I edited the indentation level (to 4 from 2) and the maximum line length. That's two lines, right at the top of the script. (BTW there are ~350 lines wider than the original limit, so that's likely fixable gradually.)

It will be my first time with Perl, but otherwise it should probably be easy to make these two parameters configurable.

**Comment by vszakats** [comment]
Customisable `checksrc.pl` added in https://github.com/libssh2/libssh2/pull/236

**Comment by vszakats** [comment]
Remaining warnings:
```
./agent.c:300:5: warning: use of sprintf is banned (BANNEDFUNC)
     sprintf(mapname, "PageantRequest%08x", (unsigned)GetCurrentThreadId());
     ^
./channel.c:1165:17: warning: use of sprintf is banned (BANNEDFUNC)
                 sprintf((char *)&s[i*2], "%02X", buffer[i]);
                 ^
./knownhost.c:958:12: warning: use of non-binary fopen without FOPEN_* macro: r (FOPENMODE)
     file = fopen(filename, "r");
            ^
./knownhost.c:1182:12: warning: use of non-binary fopen without FOPEN_* macro: w (FOPENMODE)
     file = fopen(filename, "w");
            ^
./libgcrypt.c:177:10: warning: use of non-binary fopen without FOPEN_* macro: r (FOPENMODE)
     fp = fopen(filename, "r");
          ^
./libgcrypt.c:289:10: warning: use of non-binary fopen without FOPEN_* macro: r (FOPENMODE)
     fp = fopen(filename, "r");
          ^
./mbedtls.c:283:9: warning: assignment within conditional expression (ASSIGNWITHINCONDITION)
     if((ret = mbedtls_mpi_read_binary(&(ctx->E), edata, elen) ) != 0 ||
         ^
./mbedtls.c:293:13: warning: assignment within conditional expression (ASSIGNWITHINCONDITION)
         if((ret = mbedtls_mpi_read_binary(&(ctx->D), ddata, dlen) ) != 0 ||
             ^
./mbedtls.c:1:1: error: Missing copyright statement (COPYRIGHT)
 
 ^
./userauth.c:546:10: warning: use of non-binary fopen without FOPEN_* macro: r (FOPENMODE)
     fd = fopen(pubkeyfile, "r");
          ^
./wincng.c:557:10: warning: use of non-binary fopen without FOPEN_* macro: r (FOPENMODE)
     fp = fopen(filename, "r");
          ^
./mbedtls.h:1:1: error: Missing copyright statement (COPYRIGHT)
 
 ^
checksrc: 0 errors and 12 warnings
```

**Comment by vszakats** [comment]
Addresses the remaining 22 warnings.

**Comment by vszakats** [comment]
Pushed in these commits:
e54ef175d4ab44b6832798bb7e60474f85b0305c
c274a3fdd41dc8268e2fcb8206fb19839a572826
ef6eaadba51985319ad18661ef54a273a3867c59
e1d8c63476f1282692251369e37b53850065cdd8

**Pull request closed without merging**
