### PR TITLE
Update for SFTP-reAD

### PR DESCRIPTION
**Pull request by LarsNordin-LNdata**
hI,

Sorry for the revert and revert-revert, I need to write down the steps to update the source via GIT.

/Lars

### CODE REVIEW

**Comment by bagder** [comment]
So the two reverts can simply be ignored?

**Comment by bagder** [comment]
I merged the first commit and pushed it as commit d754fee2f2 (immediately after the 1.6.0 release to give it time to get tested before we ship it). Good enough you think?

**Comment by LarsNordin-LNdata** [comment]
On 2015-06-12 09:17, Daniel Stenberg wrote:
>
> I merged the first commit and pushed it as commit d754fee 
> <https://github.com/libssh2/libssh2/commit/d754fee2f24565d8c89dc37a7f05ba1222a7bfc4> 
> (immediately after the 1.6.0 release to give it time to get tested 
> before we ship it). Good enough you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/libssh2/libssh2/pull/18#issuecomment-111389855>.
>
Yes, it gives me time to do some testing of the BUFFER_SIZE value or if 
it shuld be configurable via a new function.

Thanks!

/Lars

**Comment by LarsNordin-LNdata** [comment]
On 2015-06-12 08:27, Daniel Stenberg wrote:
>
> So the two reverts can simply be ignored?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/libssh2/libssh2/pull/18#issuecomment-111376854>.
>
Yes!

/Lars

**Pull request closed without merging**
