### PR TITLE
Support RSA certificate authentication

### PR DESCRIPTION
**Pull request by msabansal**
This PR is based of https://github.com/libssh2/libssh2/pull/570/files and just the tests were fixed to make sure everything works smoothly.

### CODE REVIEW

**Comment by mback2k** [comment]
It seems like the tests are broken on Windows. You can re-run be doing an amend and force-push.

**Comment by msabansal** [comment]
@mback2k just to clarify by tests are broken you mean this seems to be a flaky test?

**Comment by mback2k** [comment]
No, in that case the tests themselves are not flaky, just the CI platform is sometimes.

**Comment by msabansal** [comment]
got it thanks for the clarification. Running the tests again.

**Comment by msabansal** [comment]
Can someone please review and if there is a follow up please let me know.

**Comment by msabansal** [comment]
@willco007 Checking if you can take a look at this.

**Pull request merged**
