### PR TITLE
KNOWNHOST_CHECK_ define values

### PR DESCRIPTION
**Pull request by willco007**
Change LIBSSH2_KNOWNHOST_CHECK_* error values so their values don't collide with LIBSSH2_FX_* defined codes to make error matching easier.

### CODE REVIEW

**Comment by willco007** [comment]
Ugh, sorry about the pull request mess. I really only wanted the known_hosts defines file.

**Comment by bagder** [comment]
Ok, I sympathize with what you're trying to do here but this change breaks the ABI. Applications built against 1.5.0 will not work with a version compiled with this...

**Comment by willco007** [comment]
Yeah, OK. Perhaps revisit with the next major release?

**Comment by bagder** [comment]
Fair enough, added milestone for that to make it findable.

**Comment by bagder** [comment]
Closed for now.

**Pull request closed without merging**
