### PR TITLE
Add an EWOULDBLOCK check for better portability

### PR DESCRIPTION
**Pull request by hlefebvre**
Proposal for fixing #171

### CODE REVIEW

**Comment by hlefebvre** [comment]
Hi,
I do not know how to 'rebase' it with github but resolving conflicts looks to work.

**Comment by bagder** [comment]
Don't rebase it with github (if that is even possible I don't know). Just rebase your local branch with git like normal and force-push the fix to the branch.

**Comment by hlefebvre** [comment]
I've tried checking out the repository and rebasing with command line.
$ git status
On branch fix-171
Your branch is up to date with 'origin/fix-171'.

nothing to commit, working tree clean
$ git rebase origin/HEAD
Current branch fix-171 is up to date.

I never use gitlab's git, it must have something to do with local repo being 1 year old fork.

**Comment by bagder** [comment]
`git rebase origin/master` is what I typically run for that (assuming you have an origin/master that is updated). The age of the fork shouldn't matter

**Comment by hlefebvre** [comment]
I found out how to do it (looks to have worked).
origin was my fork so I added another origin
git remote add github https://xxxxxxx
git rebase github/master
## fix conflicts
git rebase --continue
git push

hope I will be ok

**Comment by willco007** [comment]
@hlefebvre could you fix the linter issues found in the latest travis builds? Then we'll get it integrated.

**Comment by hlefebvre** [comment]
@willco007 should be ok now

**Pull request merged**
