### PR TITLE
Test CI build without HAVE_EVP_AES_128_CTR

### PR DESCRIPTION
**Pull request by jeroen**
This PR is not to be merged, but only used to trigger a CI run to test a configuration without `HAVE_EVP_AES_128_CTR`.

It shows that the implementation is broken for a configuration without `HAVE_EVP_AES_128_CTR`. This is not tested in regular CI runs. See also: https://github.com/libssh2/libssh2/issues/739

The best solution is to remove this test from autoconf/cmake, and always assume/require `EVP_aes_128_ctr` is available, and remove the fallback implementation. `EVP_aes_128_ctr` has been available for a very long time, but sometimes cmake/autoconf fails to properly detect it.

### CODE REVIEW

**Comment by willco007** [comment]
Could you re-run this with this PR merged? https://github.com/libssh2/libssh2/commit/3fdcff2485a29544e974bf1d73dd5cfd275c6a47

**Comment by jeroen** [comment]
Yeah that fixes it. Still though I think it would be better to remove the obsolete `HAVE_EVP_AES_128_CTR` stuff to prevent this from re-appearing in the future.

**Comment by willco007** [comment]
That PR fixes the ciphers used when AES_128 is disabled. While I agree removing this probably is fine, it also doesn't hurt having it around and removing it won't fix the underlying issue (which was a bug fixed in https://github.com/libssh2/libssh2/commit/3fdcff2485a29544e974bf1d73dd5cfd275c6a47).

**Comment by willco007** [comment]
I guess that does leave the issue with autoconf not picking it up which is still a bit mysterious.

**Comment by jeroen** [comment]
> I guess that does leave the issue with autoconf not picking it up which is still a bit mysterious.

This happened because it was a windows environment with a static openssl, that needs additional linker flags to build a test program.

**Pull request closed without merging**
