### PR TITLE
Meson build scripts added

### LINKED ISSUE #725: add meson build system
everything is in the title. Advantages : 
 * simpler syntax than cmake
 * a bit faster than cmake
 * it just works, no hacks like one can find in cmake
 * cross-compilation is easier to set up
 * options are clearly available in a separate file, no need to find them in all the CMakeLists.txt or in cmake/
 * you can you wrap feature to get dependencies like glig2 or gstreamer projects are doing

### PR DESCRIPTION
**Pull request by ilsme**
Fixes #725

### CODE REVIEW

**Comment by ilsme** [comment]
#725

**Comment by vtorri** [comment]
very nice!

**Comment by vtorri** [comment]
any review of this PR ?

**Comment by vtorri** [comment]
@ilsme maybe there should be more options: look at all the AC_ARG_* commands in configure.ac

**Comment by vtorri** [comment]
add wolfSSL and WinCNG crypto backend

**Comment by ilsme** [comment]
@vtorri you're welcome to add it by yourself

**Comment by vtorri** [comment]
@ilsme i'll be happy to provide a PR if your PR will be applied.

**Comment by ilsme** [comment]
@vtorri my PR was applied to wrapdb, you can add your PR there

**Comment by neheb** [comment]
@vtorri WrapDB has WinCNG, openssl, gnutls, and mbedtls but no wolfssl.

**Comment by ilsme** [comment]
@neheb wdym "have" mbedtls? I though someone added it as a separate wrap but I don't see it.

**Comment by vszakats** [comment]
After making an updated version of this PR locally, the build fails in an odd way (on macOS), see below. Also there have been a bunch of improvements with existing CMake and autotools builds, so those might work better now than earlier. They are also fairly well tested. I'm personally not very keen on adding more build tools, even though Meson looks much leaner than the classic ones.

@libssh2/dev-team What do you think?

```
[1/24] Compiling C object libssh2.1.dylib.p/src_global.c.o
FAILED: libssh2.1.dylib.p/src_global.c.o 
cc -Ilibssh2.1.dylib.p -I. -I.. -I../include -I/usr/local/include/ -fcolor-diagnostics -Wall -Winvalid-pch -O0 -g -DLIBSSH2_MBEDTLS -MD -MQ libssh2.1.dylib.p/src_global.c.o -MF libssh2.1.dylib.p/src_global.c.o.d -o libssh2.1.dylib.p/src_global.c.o -c ../src/global.c
In file included from ../src/global.c:39:
../src/libssh2_priv.h:966:32: warning: declaration of 'struct iovec' will not be visible outside of this function [-Wvisibility]
                  const struct iovec datavec[], void **abstract);
                               ^
../src/libssh2_priv.h:966:45: error: array has incomplete element type 'const struct iovec'
                  const struct iovec datavec[], void **abstract);
                                            ^
../src/libssh2_priv.h:966:32: note: forward declaration of 'struct iovec'
                  const struct iovec datavec[], void **abstract);
                               ^
1 warning and 1 error generated.
```

**Comment by dfandrich** [comment]
I think we already support one build system too many.

**Comment by neheb** [comment]
@vszakats wrapdb has a newer version that works. This PR needs updating.

**Comment by bagder** [comment]
There are many cool and good build systems out there but I don't think libssh2 needs to add support for more than it already does. It complicates the lives of the maintainers for very little gain.

**Comment by vtorri** [comment]
@bagder about gain, get a computer with Windows, install MSYS2 with mingw-w64 in it. Compile curl with autotools, then with cmake. And you will see that there is a gain... meson is a bit faster than cmake. And muon (a C99 port of meson) is a quite faster than meson.

**Comment by bagder** [comment]
I am aware. I still think it is a net *cost* added to the project and its maintainers, only to give a few people slightly faster builds the few times they build it.

**Comment by vszakats** [comment]
@vtorri: speaking of speed, CMake should be faster now on Windows, due the efforts made to eliminate as much detection steps as possible. We also still have `Makefile.mk` (formerly known as `win32/GNUmakefile`), which doesn't have a detection phase at all on Windows, making it the fastest by a good margin.

**Comment by jas4711** [comment]
+1 to focus on autoconf which is the most flexible/portable.  I agree multiple build systems costs more than it gives back to the project.

**Comment by neheb** [comment]
The issue with autoconf is its buggyness and slow compilation speed. I'd at least get rid of it and keep only CMake.

**Comment by vszakats** [comment]
CMake provides MSVC support (autotools doesn't), which seems to justify supporting it next to autotools. After recent updates, both should work equally well for most cases and have fairly good feature parity. Both are here to stay I believe. Also, all build tools now share common input source lists, so there is no need anymore to maintain parallel ones. (Meson would re-add a second source list, and it doesn't support reusing `Makefile.inc` as far as I could tell.)

(Disclaimer: not a fan of either of autotools/CMake and also not an MSVC user.)

**Comment by vszakats** [comment]
Thanks for the input to everyone. The conclusion is that we are not planning to add a new build system. Having said that it was interesing to hear about Meson, Muon and ninja a giving them a shot.

Also opened PR #1025 deleting one more detection step to make CMake init a bit faster.

**Comment by vszakats** [comment]
In my experience for projects of sizes comparable to libssh2 (= smaller ones), CMake and autotools are slow on Windows because of their often inflated detection phase. On Windows, file ops are very slow and detections are effectively compiling a whole .exe each. Since it's easy to add more detections, projects tend to accumulate a lot of them, making them slow. Also Windows is a fairly static environment, so most of these detections have predictable results so mostly avoidable with little downside.

The compilation/linking phase is bound to the toolchain's speed, and doesn't depend much on the build tool. (again for smaller projects like libssh2). This phase could be sped up by invoking the compiler a single time for all the sources, but interestingly none of the build tools do that (not even Meson), even though all compilers support it.

One more thing we can do to speed up CMake for libssh2 on Windows, is to avoid detections completely and rely on the recently built-in and streamlined internal Win32 configuration. I.e. skip all detections, and avoid defining `HAVE_CONFIG_H`, then tackle fallouts. Note that I've done that for quite a bit of detections already.

**Comment by neheb** [comment]
Oh you mean __has_include? That’s a C++17 feature AFAIK.

**Comment by vszakats** [comment]
No, I meant to use this with CMake (though on a second thought, I'm not sure it's a good idea, as it would introduce surprising/unexpected behaviour): https://github.com/libssh2/libssh2/blob/272a17ce266b4428c95c5337925aababc4acfa53/src/libssh2_setup.h#L22-L44

With the patch linked above we'll be down to [6 detections](https://ci.appveyor.com/project/libssh2org/libssh2/builds/46958280) on Windows with MSVC, 8 with clang/mingw64, 11 with gcc/mingw64. This is down from 32 for MSVC [two months ago](https://ci.appveyor.com/project/libssh2org/libssh2/builds/46958280). All this while adding picky warnings, which used to require many dozens of extra detections, but that also got almost completely eliminated (to 3 with gcc).

Compilation should also be faster after recent changes, e.g. on Windows `WINDOWS_LEAN_AND_MEAN` is universally enabled, with more similar options added and eliminated most duplicate or unnecessary includes, amongst them many Windows ones. We also have less compiler invocations due to the side-effect of compiling some sources as one unit (e.g. `blowfish.c` or `agent_win.c`). I've also added `TrackFileAccess=false` eliminating some VS wrapper we don't need with MSVC (perhaps this should be limited to our CI, I couldn't find much background info on its purpose). Enabling parallel builds can also reduce build times quite noticeably (our CI now uses `make -j3` and `cmake --build ... --parallel 3`).

Unless we expect `poll()` support to appear on Windows anytime soon, we might exclude that one from CMake detection as well.

Have you tried compiling a recent master branch?

**Comment by bagder** [comment]
> I’m in favor of getting rid of autoconf.

I would be strongly against that. Call me conservative and old-fashioned but I have played this game (Open source) for a long time, and my experience have so far been that autotools is well-known, survives and is pretty much the only system that generates build files that can run on systems without them first having to install a new build toolset. This often makes autotools the only system that that still works on legacy things from the past. And I value stability, portability and accessibility before a minor increase in build-time. This project is tiny and builds fast anyway. IMHO.

**Comment by neheb** [comment]
And in my experience with OpenWrt autotools is slow and buggy (read: compilation failure).

I've spent a considerable amount of time migrating as many packages as possible from autotools to CMake/meson and at this point, the whole compilation process is faster and less likely to break.

**Comment by bagder** [comment]
> And in my experience with OpenWrt autotools is slow and buggy (read: compilation failure).

Slow, yes. Buggy: not in general. That's mostly not because of autotools, but because of wrong/bad use of it.

You win *nothing* by removing support for autotools in libssh2, but you lose something.

**Comment by vszakats** [comment]
Predefining certain things is perfectly safe on Windows, as the environment is fairly static. The hand-crafted config was (as `win32/libssh2_config.h`) and is used with build tools without detection logic, like `Makefile.mk`, `NMakefile` and anyone building libssh2 via Visual Studio's own build facilities, aka anyone without a `config.h`.

We have ~40 GitHub Actions, but there is no job there that uses CMake on Windows. Maybe I should add one for clang and gcc. Or what do you mean by regular GitHub Actions?

**Comment by neheb** [comment]
Looking again, it seems it's currently done: https://github.com/libssh2/libssh2/blob/master/.github/workflows/ci.yml#L164

clang-cl is not tested though. Might get some useful warnings if compiling with /Wanalyzer

**Comment by vszakats** [comment]
That's testing CMake with MSVC. What's missing is CMake + mingw-w64 + clang/gcc.

**Comment by vszakats** [comment]
After some updates done yesterday, CMake detections are down to zero for MSVC and MinGW + clang, and down to 3 for MinGW + gcc (that can be zeroes by disabling picky warnings). Configuration takes just a few seconds now.

**Comment by vszakats** [comment]
Also added "unity" builds for CMake: #1034. This should boost build times to a few seconds per lib flavour. E.g. on macOS it's below 1 second. For Windows clang cross-builds it's below 5 seconds (after 1.5s configuration), on old hardware.

**Pull request closed without merging**
