### PR TITLE
Generate debug info when building with MSVC

### PR DESCRIPTION
**Pull request by jethrogb**
I'm not sure why the Visual Studio generators wouldn't do this automatically. I copied what libgit2 is doing.

### CODE REVIEW

**Comment by jethrogb** [comment]
@alamaison @wildart @dbyron0 ping

**Comment by dbyron0** [comment]
Sorry, I imagine this is right but know very little about cmake.

**Comment by jethrogb** [comment]
@alamaison @wildart @dbyron0 ping

**Comment by alamaison** [comment]
Don't you just need to switch to the Debug or RelWithDebugInfo configuration in the generated visual studio project?

**Comment by jethrogb** [comment]
It's been a long time. I think I tried that but it didn't work. Do you want me to check again?

**Comment by jethrogb** [comment]
Instead of marking it stale, maybe just merge it?

**Comment by bagder** [comment]
Anyone (else) building on Windows who can say something :+1: or :-1: about this PR?

**Comment by jethrogb** [comment]
not stale

**Comment by willco007** [comment]
@jethrogb did you happen to test the suggestion from @alamaison about changing the project configuration?

**Comment by jethrogb** [comment]
Ok I finally booted into Windows to test this flow again. I'm not using the graphical Visual Studio interface to build anything. I'm just using CMake for the entire build. I confirmed that it still doesn't generate symbols without this change.

**Pull request merged**
