### PR TITLE
Build Error

### PR DESCRIPTION
**Pull request by zhaochongliu**
The build cannot be successful because of the following error:

`#7 7.381 [ 72%] Building C object tests/CMakeFiles/test_keyboard_interactive_auth_info_request.dir/test_keyboard_interactive_auth_info_request.c.o
#7 7.385 cc: error: unrecognized command line option '-fprofile-abs-path'; did you mean '-fprofile-generate'?
#7 7.385 tests/CMakeFiles/test_keyboard_interactive_auth_info_request.dir/build.make:62: recipe for target 'tests/CMakeFiles/test_keyboard_interactive_auth_info_request.dir/test_keyboard_interactive_auth_info_request.c.o' failed`

Delete the option `-fprofile-abs-path` works for me.

### CODE REVIEW

**Comment by willco007** [comment]
This option was added to gcc 8. What are you attempting to build on?

**Comment by zhaochongliu** [comment]
Yes. I am using gcc 7. 
Will upstream a change that detects the gcc version.

**Comment by zhaochongliu** [comment]
@willco007 Hi, I have added the gcc version detection part and build successfully locally. 
Not sure why it failed in AppVeyor. 
Could you please check it out? Thanks.

**Comment by willco007** [comment]
Instead of parsing the GCC version ourselves, it may be better to use the CMake constant `CMAKE_C_COMPILER_VERSION` or `CMAKE_CXX_COMPILER_VERSION`.

**Comment by zhaochongliu** [comment]
@willco007 Thanks for your suggestion. Changed already. But failed in the password authentication test case.  Should not be related to my change...

**Comment by zhaochongliu** [comment]
@willco007 Will you add this change in the main branch?

**Pull request merged**
