### PR TITLE
Added support for OpenSSL_1_1_0

### PR DESCRIPTION
**Pull request by tholberton**
Added getters and setters for opaque types `DSA` `DSA_SIG` and `RSA`.

### CODE REVIEW

**Comment by bagder** [comment]
It might fix #17

**Comment by vszakats** [comment]
Can this patch be extended/updated to enable the new `HAVE_` options inside the source whenever OpenSSL 1.1.0 is detected? This would make this build-system agnostic.

Adding these lines to `src/openssl.h` could work:
```c
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
# define HAVE_DSA_GET0_KEY
# define HAVE_DSA_SET0_PQG
# define HAVE_DSA_SET0_KEY
# define HAVE_DSA_SIG_GET0
# define HAVE_DSA_SIG_SET0
# define HAVE_RSA_GET0_KEY
# define HAVE_RSA_SET0_KEY
# define HAVE_RSA_SET0_FACTORS
# define HAVE_RSA_SET0_CRT_PARAMS
#endif
```

**Comment by tholberton** [comment]
@vszakats I could do that. But, it would make more sense to me to put it into `src/openssl.c` like this:

```
#ifdef OPENSSL_VERSION_MAJOR >= 0x101
```

**Comment by vszakats** [comment]
@tholberton Even better that way.

**Comment by vszakats** [comment]
I missed `HAVE_DSA_GET0_PQG` from the top of the list of my snippet. Can you add it as well?

```c
# ifndef HAVE_DSA_GET0_PQG
#  define HAVE_DSA_GET0_PQG 1
# endif
```

**Comment by vszakats** [comment]
With the `HAVE_DSA_GET0_PQG` modification, libssh2 builds fine against OpenSSL 1.1.0 using this patch:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.890#L2501

Basic SSH/SFTP test also worked fine.

**Comment by tholberton** [comment]
I was actually thinking that it would be better to do something like this:
```
#if OPENSSL_VERSION_NUMBER < 0x10100000L
static void DSA_get0_pqg(const DSA * dsa, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g){
    if (p != NULL){
        *p = dsa->p;
    }
    /* ... */
}
/* ... */
#endif
```
And remove the functions checks in the build system and the `ifdef` sections in the code that I original wrote. It would look a lot cleaner and completely avoid build system code. I can write it with a minimal diff and you can just squash the merge to get rid of the work in between.

**Comment by vszakats** [comment]
Perhaps it'd be enough to use the existing `HAVE_OPAQUE_STRUCTS` macro to replace the multiple `HAVE_*` ones, while keeping the current source modifications (which I think it's nice and pure, and would be somewhat obfuscated by using new static functions). Since this macro is already defined, all special cmake logic can be dropped, along with their definitions on top of `openssl.c`.

**Comment by willco007** [comment]
I agree with @vszakats; having defines for every function seems unnecessary as they are OpenSSL specific. I would piggy back off the HAVE_OPAQUE_STRUCTS defined in the the header; perhaps renaming it to HAVE_OPAQUE_OPENSSL or something similar.

**Comment by vszakats** [comment]
`HAVE_OPAQUE_OPENSSL` is slightly misleading as `HAVE_OPAQUE_STRUCTS` already applies to OpenSSL, plus the former may apply to BoringSSL/LibreSSL as well in the future. For these reasons, I feel the name `HAVE_OPAQUE_RSADSA` (or similar) would better tell its purpose. It's just a minor concern though.

Test builds against OpenSSL 1.1.0 are successful:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.897

**Comment by willco007** [comment]
There is a typo in this commit; line 188 should be:

DSA_set0_pqg(*dsactx, p_bn, q_bn, g_bn);

**Comment by willco007** [comment]
@vszakats My thought was we could add HAVE_OPAQUE_LIBRE, etc if they applied these API changes as well. However, that may get cumbersome down the road. Perhaps a wait and see approach is best for now?

**Comment by vszakats** [comment]
@willco007 Yes, having to maintain different (and possibly colliding) fork-specific feature-sets can easily become a problem. I'd expect the forks to keep it sane and either not endorse certain OpenSSL updates or apply them in a compatible fashion. (We shall see)

Taking a peek at sister project `libcurl`, there the macro name chosen for the purpose at hand was `HAVE_OPAQUE_RSA_DSA_DH`, so I suggest to use the same name here.

**Comment by vszakats** [comment]
On a second (third?) look, the correct macro definition would be:
```
#if OPENSSL_VERSION_NUMBER >= 0x10100000L && \
    !defined(LIBRESSL_VERSION_NUMBER)
# define HAVE_OPAQUE_RSA_DSA_SH 1
#endif
```
This can be merged with the block defining `HAVE_OPAQUE_STRUCTS` in `openssl.h`.

**Comment by willco007** [comment]
My thought about that this name is if Libre or Boring don't implement the exact same API we're back to multiple defines for opaque structures.  Having it named something OpenSSL specific would be a hint to the user these calls are OpenSSL specific which may eliminate confusion in the future.

**Comment by vszakats** [comment]
To get around the naming issue altogether, existing `HAVE_OPAQUE_STRUCTS` macro can be used in this patch. It will make these modifications work with all existing LibreSSL and OpenSSL versions.

**Comment by tholberton** [comment]
My thought on the macro name is that `HAVE_OPAQUE_STRUCTS` is exceeding broad. The names `HAVE_OPAQUE_DSA` and `HAVE_OPAQUE_RSA` make a lot of sense to me. The name `HAVE_OPAQUE_OPENSSL` seems like a decent compromise.

**Comment by vszakats** [comment]
Merged, thank you @tholberton!

**Pull request merged**
