### PR TITLE
Basic dockerised test suite.

### PR DESCRIPTION
**Pull request by alamaison**
This PR introduces a test suite for libssh2.  It runs OpenSSH in a Docker container because that works well on Windows (via docker-machine) as well as Linux.  Presumably it works on Mac too with docker-machine, but I've not tested that.

Because the test suite is docker-machine aware, you can also run it against a cloud provider, for more realistic network testing, by setting your cloud provider as your active docker machine.  The Appveyor CI setup in this PR does that because Appveyor doesn't support docker locally.

This is based on my 'old trusty' test suite, which I had been using to catch libssh2 errors for years, ported to C and dockerised.  I've only ported a subset of the tests so far (auth and hostkey) but I'll move the others over in due course.

Currently the Appveyor setup is running tests against my own DigitalOcean account.  That's not ideal but, assuming the costs are low, will do for now.

### CODE REVIEW

**Comment by mback2k** [comment]
Looks nice. Just out of curiosity, did you test the WinCNG implementation using this testsuite and did everything work? :-)

**Comment by alamaison** [comment]
@mback2k I hadn't, but I will do now: https://ci.appveyor.com/project/alamaison/libssh2/build/108

**Comment by alamaison** [comment]
@mback2k So the tests fail with the WinCNG backend (libssh2_session_handshake failed (-5): Unable to exchange encryption keys).

Unless the WinCNG backend is totally broken, I'm guessing the the version of OpenSSH server used in the docker image requires a key algo that WinCNG doesn't support.  The docker image is just debian:jessie with the default install of openssh-server which, at this time, is Win 6.7p1-5+deb8u3.

**Comment by mback2k** [comment]
@alamaison Yes, it seems like recent OpenSSH versions by default require at least AES-128-CTR, but WinCNG only supports CBC-mode AES for now. Could the sshd_config be enhanced to support all ciphers which are supported by libssh2?

**Comment by alamaison** [comment]
It could perhaps, though I think being able to talk to the current debian
default OpenSSL should be our baseline for considering something to be
'passing'. What would it take to get WinCNG to meet that bar?

Alex

**Comment by mback2k** [comment]
I guess the "best" approach would be to move the AES-CTR support from the libgcrypt backend into a a generic part and make it possible to use that for all backends that do not natively support AES-CTR, like WinCNG. The other missing implementations which cannot be supported using WinCNG are Blowfish and CAST.

**Comment by mback2k** [comment]
Just for reference, these are the sshd_config options to make OpenSSH accept all cipher suites supported by libssh2:
```
KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,arcfour128
MACs hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160
```

**Comment by kdudka** [comment]
Why did you remove the ```simple``` and ```ssh2``` test cases?

They used to work just fine on Fedora builders whereas the docker-based tests fail badly...

**Comment by alamaison** [comment]
Because they were flaky and not cross-platform.

When you say 'fail badly', can you give some details?

**Comment by kdudka** [comment]
On Saturday, November 12, 2016 02:39:33 Alexander Lamaison wrote:
> Because they were flaky and not cross-platform.

I did not have any problem with those tests.  In fact they still work
unless you build libssh2 with CMake.  I need a test-suite that can be
run by an unprivileged user on a regular build host.

> When you say 'fail badly', can you give some details?

$ ctest --output-on-failure
Test project /home/kdudka/fedora/libssh2/libssh2-1.8.0/libssh2_build
      Start  1: test_hostkey
 1/11 Test  #1: test_hostkey ....................................................***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  2: test_hostkey_hash
 2/11 Test  #2: test_hostkey_hash ...............................................***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  3: test_password_auth_succeeds_with_correct_credentials
 3/11 Test  #3: test_password_auth_succeeds_with_correct_credentials ............***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  4: test_password_auth_fails_with_wrong_password
 4/11 Test  #4: test_password_auth_fails_with_wrong_password ....................***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  5: test_password_auth_fails_with_wrong_username
 5/11 Test  #5: test_password_auth_fails_with_wrong_username ....................***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  6: test_public_key_auth_fails_with_wrong_key
 6/11 Test  #6: test_public_key_auth_fails_with_wrong_key .......................***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  7: test_public_key_auth_succeeds_with_correct_rsa_key
 7/11 Test  #7: test_public_key_auth_succeeds_with_correct_rsa_key ..............***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  8: test_public_key_auth_succeeds_with_correct_dsa_key
 8/11 Test  #8: test_public_key_auth_succeeds_with_correct_dsa_key ..............***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start  9: test_keyboard_interactive_auth_fails_with_wrong_response
 9/11 Test  #9: test_keyboard_interactive_auth_fails_with_wrong_response ........***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start 10: test_keyboard_interactive_auth_succeeds_with_correct_response
10/11 Test #10: test_keyboard_interactive_auth_succeeds_with_correct_response ...***Failed    0.03 sec
Error running command 'docker build -t libssh2/openssh_server openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Failed to build docker image
Cannot stop session - none startedCannot stop container - none startedCommand: docker build -t libssh2/openssh_server openssh_server

      Start 11: mansyntax
11/11 Test #11: mansyntax .......................................................   Passed    2.96 sec

9% tests passed, 10 tests failed out of 11

Total Test time (real) =   3.26 sec

The following tests FAILED:
          1 - test_hostkey (Failed)
          2 - test_hostkey_hash (Failed)
          3 - test_password_auth_succeeds_with_correct_credentials (Failed)
          4 - test_password_auth_fails_with_wrong_password (Failed)
          5 - test_password_auth_fails_with_wrong_username (Failed)
          6 - test_public_key_auth_fails_with_wrong_key (Failed)
          7 - test_public_key_auth_succeeds_with_correct_rsa_key (Failed)
          8 - test_public_key_auth_succeeds_with_correct_dsa_key (Failed)
          9 - test_keyboard_interactive_auth_fails_with_wrong_response (Failed)
         10 - test_keyboard_interactive_auth_succeeds_with_correct_response (Failed)
Errors while running CTest

**Comment by alamaison** [comment]
On Tue, 15 Nov 2016, 11:35 Kamil Dudka, <notifications@github.com> wrote:

> On Saturday, November 12, 2016 02:39:33 Alexander Lamaison wrote:
> > Because they were flaky and not cross-platform.


> I did not have any problem with those tests.


Of course. You're on the platform that they work on.

They were also only smoke test. They exercised very little of libssh2.
Using the docker container means we have more control over the server,
which means the new suite can cover the whole codebase.

In fact they still work
> unless you build libssh2 with CMake.


Yes, I left then in place for autotools which itself isn't cross-platform
so it didn't matter. For CMake build which are supposed to be cross
platform, the old tests weren't appropriate.

I need a test-suite that can be
> run by an unprivileged user on a regular build host.
>

You should be able to run them as an unprivileged user. Running a local
docker daemon required superuser involvement, but just to install the
service. Alternatively, you can use docker-machine to connect to a remote
docker daemon. We do this to get the tests to run in AppVeyor. Those tests
connect to my Digital Ocean account and run the server in docker there. See
appveyor.yml.

> When you say 'fail badly', can you give some details?
>
> $ ctest --output-on-failure
> Test project /home/kdudka/fedora/libssh2/libssh2-1.8.0/libssh2_build
> Start 1: test_hostkey
> 1/11 Test #1: test_hostkey
> ....................................................***Failed 0.03 sec
> Error running command 'docker build -t libssh2/openssh_server
> openssh_server' (exit 256): Cannot connect to the Docker daemon. Is the
> docker daemon running on this host?
>

You need to start the docker service or use docker-machine to connect to
one.

>

**Comment by kdudka** [comment]
Running tests in docker is useful but it is kind of unusual way of implementing an upstream test-suite.  The docker-based tests would be fine if they were optional and the previous tests were kept.  But as such, it is a severe downgrade compared to ```libssh2-1.7.0``` and a show stopper for the migration to CMake.

**Comment by alamaison** [comment]
On Wed, 16 Nov 2016, 10:12 Kamil Dudka, <notifications@github.com> wrote:

> Running tests in docker is useful but it is kind of unusual way of
> implementing an upstream test-suite. The docker-based tests would be fine
> if they were optional and the previous tests were kept. But as such, it is
> a severe downgrade compared to libssh2-1.7.0 and a show stopper for the
> migration to CMake.
>

The are optional. Configure with BUILD_TESTING=OFF if you don't want them.

I'd have no objections to adding back the original non-portable tests. But
given how little they tested I'm not sure that's any better than simply
disabling the tests.

>

**Comment by mback2k** [comment]
@alamaison #173 just introduced support for AES-CTR mode using WinCNG. Would you mind running your testsuite with WinCNG again? I performed my tests using the autotools builds since I could not get the ctest to work locally on Windows with msys and Docker for Windows.

**Pull request merged**
