### PR TITLE
misc.c: Delete unused static variables

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Is there anything missing from this patch, that may require further updates?

The issue fixed is not critical, just some unnecessary and unused strings included in any binary that includes libssh2. The strings seem to belong to an earlier base64 implementation. It's also causing a compiler warning when using gcc 6.1 or newer.

**Comment by vszakats** [comment]
Any love for this PR?

**Comment by kdudka** [comment]
Sorry for replying late on this!  Pushed as 1fc7c857.  Thanks for the patch!

**Comment by kdudka** [comment]
On Tuesday, August 02, 2016 18:24:23 Viktor Szakats wrote:
> Any love for this PR?

Sorry for replying late on this!  Pushed as 1fc7c857.  Thanks for the patch!

**Comment by vszakats** [comment]
No worries and thank you for the merge!

**Pull request closed without merging**
