### PR TITLE
ci: disable WinCNG tests due to flakiness

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mback2k** [comment]
Not a fan as I would rather like to find the root cause, I am out of ideas at this point.

**Comment by vszakats** [comment]
Not a good solution for sure, but having almost everything red is also confusing. For every run one needs to inspect what happened, instead of trusting the red/green mark.

Maybe automatically re-running failed WinCNG tests could work also? But that would make AppVeyor CI runs slower.
Another workaround is to let the tests run, but ignore the result.

**Comment by vszakats** [comment]
Testing the retry approach here: #1017

**Comment by vszakats** [comment]
Closing this in favour of #1017.

**Pull request closed without merging**
