### PR TITLE
Rebased/Squashed mbedTLS branch

### PR DESCRIPTION
**Pull request by Keno**
This rebases and squashes #106. I've also added support for mbedtls to the autotools build system and added some documentation on the new build system options.

### CODE REVIEW

**Comment by bagder** [comment]
`automake: error: cannot open < src/../Makefile.mbedTLS.inc: No such file or directory`

Forgot to add that file I guess?

**Comment by Keno** [comment]
yes, sorry!

**Comment by Keno** [comment]
should be fixed.

**Comment by bagder** [comment]
Yes, works now. Now I just ran into problems with the configure script. Not really your fault as you just used the same style already used, its just that it isn't very good...

**Comment by Keno** [comment]
I suppose I'm gonna have to build mbedtls from source on travis. I had hoped that wasn't necessary anymore since we don't need to patch it now, but it looks like Travis' ubuntu is too old to have the package and I couldn't find a good ppa.

**Comment by bagder** [comment]
Thanks for all the work. I merged what we have now. For follow up fixes and more, just create new issues or PRs, thanks!

**Comment by tkelman** [comment]
Fantastic, thank you so much @bagder!

**Comment by bagder** [comment]
Ah right, we need to fix the travis build. Do we revert the commit 3e6de50 to start with or do you have a fix pending?

**Comment by tkelman** [comment]
I'll try a PR

**Pull request closed without merging**
