### PR TITLE
String buffer improvements

### PR DESCRIPTION
**Pull request by willco007**
Changed `_libssh2_get_c_string` to `_libssh2_get_string` and now returns -1 on error and 0 on success. Also changed `_libssh2_get_bignum_bytes` to return -1 on error and 0 on success. Both now take `size_t` as a parameter to return the length of the buffer. This is to attempt to keep the data going in/out of these functions unsigned to better impedance match the existing API.

### CODE REVIEW

**Comment by bagder** [comment]
Will, please don't merge master into your branch. Rebase and force-push instead so that we then can just merge this fast-forward without merge commits. Makes the history and commit log much easier and simpler.

**Comment by bagder** [comment]
I would also suggest you run the checksrc script locally before you push, as it will save you some roundtrips...

**Comment by willco007** [comment]
@bagder Sorry about the merge; working on formatting at the moment.

**Comment by willco007** [comment]
Ugh, I just merged it again. Starting over.

**Pull request closed without merging**
