### PR TITLE
Add support for an OSS Fuzzer fuzzing target

### PR DESCRIPTION
**Pull request by cmeister2**
This adds support for an OSS-Fuzz fuzzing target in ssh2_client_fuzzer,
which is a cut down example of ssh2.c. Future enhancements can improve
coverage.

---

I've tested this with the oss-fuzz framework and it appears to find repeated READ access bugs in one particular function, so I think it's definitely worth getting in!

### CODE REVIEW

**Comment by tiennou** [comment]
Thanks for working on this, I had prodded oss-fuzz around but decided that more tests would be most helpful (and I've never done anything fuzzing-related yet so…) !

The read bugs you're seeing could be the ones from #386 (hopefully). Other possible ennhancements would be to wire your fuzzing socket to the test harness in #243, so you get those systems as well. I have a branch on top of it with more partially-written tests. Another low-hanging fruit would be the `SSH_AGENT_*` socket.

I can't do much more because I've only been involved in this project recently, so those are only suggestions 😉.

**Comment by cmeister2** [comment]
> The read bugs you're seeing could be the ones from #386 (hopefully). 

Unfortunately not! I reported them to the security DL last week though :smile:

**Comment by willco007** [comment]
@cmeister2 Thanks for all your work on this! There is a pending PR to overhaul the test system; would you mind updating this after that is landed?

**Comment by cmeister2** [comment]
Sure, can you ping me when that happens?

**Comment by cmeister2** [comment]
Ok, so just wondering what the status on this is. We're currently getting overnight issues off a branch I'm maintaining (and @willco007 is doing a stellar job of fixing them), but it'd be good to get this code into master if possible.

**Comment by cmeister2** [comment]
(Or if you didn't want to get it into master, you could create a new libssh2-fuzzer repository or something and give me write access to that; similar to https://github.com/curl/curl-fuzzer/ or https://github.com/GNUAspell/aspell-fuzz/ )

**Comment by willco007** [comment]
There is still work that needs to be done on #243 before it can be landed. I don't think it's necessary to create a new repro just for the fuzzer; but I could be convinced if others feel strongly about it.

**Comment by cmeister2** [comment]
Think I'm still waiting on a merge here which @willco007 seemed to want to move forward with, as per https://github.com/libssh2/libssh2/issues/393#issuecomment-545070770

**Comment by willco007** [comment]
I'm going to land this if there is no objections, it's been sitting here for a while and in important to get integrated.

**Comment by cmeister2** [comment]
Still waiting... :smile:

**Pull request merged**
