### PR TITLE
fix support for LibreSSL after having added OpenSSL 1.1.0-pre1/2 support

### PR DESCRIPTION
**Pull request by vszakats**
Test log: https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.478

### CODE REVIEW

**Comment by vszakats** [comment]
Test log: https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.478

**Comment by asavah** [comment]
Indeed this fixes building libssh2 against libressl-portable git tree.

**Comment by bagder** [comment]
So how's the status of this when I've just merged the openssl 1.1.0 pre3 PR ?

**Comment by vszakats** [comment]
This patch remains required after applying the other one.

**Comment by bagder** [comment]
It does add a lot of `#ifdef` lines with lots of details. What would you say about making the code like this instead:

At the top of the file:
~~~
#if OPENSSL_VERSION_NUMBER >= 0x10100000L && \
    !defined(LIBRESSL_VERSION_NUMBER)
#define HAVE_OPAQUE_PKEY 1
#endif
~~~

... and then further down we only do `#ifdef HAVE_OPAQUE_PKEY` when we have that difference. I think it'll make the code gentler on the eye.

**Comment by vszakats** [comment]
I was "too fast" with a previous set of patches, where applying OpenSSL 1.1.0-pre1/2 updates. They consequently broke comparibility with LibreSSL (which apparently didn't follow the struct opacity changes of OpenSSL as of yet). This patch disables those updates using the same #if checks as used in curl sources, when compiled against LibreSSL.

**Comment by vszakats** [comment]
I agree. Will rework this later today accordingly, if that's fine with you.

**Comment by bagder** [comment]
Thanks!

**Comment by vszakats** [comment]
I've updated the patch. Chosen a more generic name for the macro, no change otherwise. [Test build](https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.589) went fine.

**Comment by vszakats** [comment]
Rebased on master and updated to use the new macro for the previously applied patch 298f056fd6931e5e8bedc4fce5142a46c8f9f4b9 as well.

**Comment by bagder** [comment]
thanks!

**Pull request closed without merging**
