### PR TITLE
lib: detect and use `bzero()` if available

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://github.com/curl/curl/pull/13589
Closes #1387

### CODE REVIEW

**Comment by vszakats** [comment]
According to https://www.man7.org/linux/man-pages/man3/bzero.3.html, `bzero()` doesn't give guarantees, making it like `memset()`.

**Comment by willco007** [comment]
This commit checks for bzero but then uses explicit_bzero(), was that intentional?

**Comment by vszakats** [comment]
This was a mistake, `bzero()` is not a secure way to zero memory. Closed without merging when I realized.

**Comment by willco007** [comment]
Oh sure, I missed you closed without merging. 👍

**Pull request closed without merging**
